# Generated by Django 5.0.1 on 2024-02-05 07:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0a38e7be-115c-4889-aa14-4b2580bb6928'), editable=False, primary_key=True, serialize=False),
        ),
    ]
