# Generated by Django 5.0.1 on 2024-02-05 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_todo_created_at_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('12387468-de0d-43ca-84af-b42ffe2ff60a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
