# Generated by Django 5.0.1 on 2024-02-06 04:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_todo_uid_timingtodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('455fe3d4-8571-4d18-9b55-52ac22a2ca8f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('455fe3d4-8571-4d18-9b55-52ac22a2ca8f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
