# Generated by Django 5.0.1 on 2024-02-06 05:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_timingtodo_uid_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('91022986-215f-4949-aa37-122e6a7ad19b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('91022986-215f-4949-aa37-122e6a7ad19b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
