# Generated by Django 5.0.1 on 2024-02-06 05:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_timingtodo_uid_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('46e28c04-5c15-4561-a88f-a77d4bacbc43'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('46e28c04-5c15-4561-a88f-a77d4bacbc43'), editable=False, primary_key=True, serialize=False),
        ),
    ]
